# Generated by Django 4.0.3 on 2022-04-02 19:16

import MyLibrary.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(2), MyLibrary.common.validators.validate_only_letters]),
        ),
    ]
