# Generated by Django 4.0.3 on 2022-04-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='end_read_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
