# Generated by Django 4.0.3 on 2022-04-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_author_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='icon',
            field=models.URLField(blank=True, default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtObUcm2uXIDJRCDiR9LR78ELprMevIEf8-w&usqp=CAU', null=True),
        ),
    ]
